spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# CAMBIO AQUÍ: Deja que Hibernate cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

# CAMBIO AQUÍ: Desactiva el init.sql que tiene el error de PostgreSQL
spring.sql.init.mode=never